spring:
  datasource:

    url: ${DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  notifications:
    recipient-email: ${NOTIFICATION_RECIPIENT}

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

