spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 10000
          writetimeout: 10000

app:
  notifications:
    standard-recipients: ${NOTIFICATION_RECIPIENT_STANDARD}
    special-recipients: ${NOTIFICATION_RECIPIENT_SPECIAL}
    days-before-expiry: 28
    renotify-after-days: 5
  storage:
    bucket: aziendale_docs
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false